ALTER TABLE "HR"."CALENDAR" ADD CONSTRAINT PK_CALENDAR PRIMARY KEY ("LISTING_ID", "THE_DATE");
-- Add Primary Key to LISTING table (if not already present)
ALTER TABLE "HR"."LISTING" ADD CONSTRAINT PK_LISTING PRIMARY KEY ("ID");
-- Add Primary Key to HOST table
ALTER TABLE "HR"."HOST"
ADD CONSTRAINT PK_HOST PRIMARY KEY ("ID");
-- Add Primary Key to NEIGHBOURHOODS table
ALTER TABLE "HR"."NEIGHBOURHOODS"
ADD CONSTRAINT PK_NEIGHBOURHOODS PRIMARY KEY ("NEIGHBOURHOOD");
-- Add Primary Key to REVIEWS table
ALTER TABLE "HR"."REVIEWS"
ADD CONSTRAINT PK_REVIEWS PRIMARY KEY ("ID");
-- Add Composite Primary Key to CALENDAR table
ALTER TABLE "HR"."CALENDAR"
ADD CONSTRAINT PK_CALENDAR PRIMARY KEY ("LISTING_ID", "THE_DATE");
